# API to contact for IP Address
api_address: "https://api.ipify.org"

cloudflare:
  zone_id:
  record_id:

  # Domain to update, e.g. mc.server.com
  domain:

  # Cloudflare API Token
  api_token:
  proxied: true
  ttl: 3000